name: Development Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  AWS_REGION: "us-west-2"
  AWS_ACCOUNT_ID: "891377056770"
  REPO_NAME: "steampipe-plugin-aws"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Git Commit SHA
        id: vars
        run: echo "GIT_COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
      - name: Build steampipe-plugin-aws docker image
        run: |
          docker builder prune -f
          docker build . --file Dockerfile --no-cache --progress=plain --tag ${{ env.REPO_NAME }}:${{ env.GIT_COMMIT_SHA }}
      - name: Tag steampipe-plugin-aws docker image
        run: docker tag ${{ env.REPO_NAME }}:${{ env.GIT_COMMIT_SHA }} ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/${{ env.REPO_NAME }}:${{ env.GIT_COMMIT_SHA }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Push images to ECR
        run: docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/${{ env.REPO_NAME }}:${{ env.GIT_COMMIT_SHA }}